# Generated by Django 5.0.6 on 2024-06-11 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Welcome to our site', max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('background_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('text_color', models.CharField(default='#000000', max_length=7)),
            ],
        ),
    ]
